% Realiza a comparação de dados de predição do HTZ

dadosPredicao = {'Radio_FM_Carangola_Hata_30m', ...
    'Radio_FM_Carangola_1812_10m', ...
    'Radio_FM_Carangola_1812_30m', ...
    'Testset_1812_10m', ...
     'TVD_Anhanguera_1812_30m'};

predicaoHTZ = {'102_1_Carangola_P1812_10m', ...
                '102_1_Carangola_P1812', ...
                'Comparacao_P1812_Carangola_10m', ...
                'Comparacao_P1812_Carangola_10m_AIR6419', ...
                'Comparacao_P1812'};

config = menu('Escolha uma configuração de predição:', dadosPredicao);

arquivoDadosPredicao = strcat('tests/config/', dadosPredicao{config}, '.m');

config = menu('Escolha um conjunto de dados gerados pelo HTZ:', predicaoHTZ);
arquivoDadosHTZ = strcat('tests/results/', predicaoHTZ{config}, '.csv');

compara = utils.compara_HTZ(arquivoDadosPredicao, arquivoDadosHTZ);

disp("Os dados de comparação estão disponiveis na variável compara.")

