%--------------------------------------------------------------------------
% Entrada de dados para predição de cobertura
% eNB em Cuiabá, modelo ITUR P.526, dados de relevo com resolução de 10 m
% e dados de classificação de estruturas
%--------------------------------------------------------------------------

%configRede = readtable("tests/data/Nextim_5G_MT 1.csv", "VariableNamingRule", "preserve");
configRede = readtable("/home/mlnunes/Documentos/dev/matlab/propagação/tests/data/Nextim_5G_MT 1.csv", "VariableNamingRule", "preserve");
fileFolder = fileparts(mfilename('fullpath'));
n = 1;
dadosPredicao = struct('modeloPredicao', 'P.526', ...
                           'frequencia', configRede{n,'Freq_TX'} * 1e6, ...
                           'dadosRelevo', 'tests/data/cuiaba_crop_dem.tif', ...
                           'dadosClutter', 'tests/data/cuiaba_crop_clu.tif', ...
                           'Movel', struct('Antena', struct('Altura',  1.6)), ...
                           'Base', struct('Nome', configRede{n, 'Cell'}, ...
                           'Latitude', configRede{n, 'Lat'}, ...
                           'Longitude', configRede{n, 'Lon'}, ...
                           'Potencia', 53.15, ...
                           'Antena', struct('Altura', configRede{n, 'Altura'} , ....
                           'ArquivoDados', fullfile( fileFolder, '..', 'data', 'antenas', configRede{n, 'Antenna_Model'}), ...
                           'Modelo', 'AIR6419', ...
                           'Funcao', 'TX', ...
                           'Azimute', configRede{n, 'Azimute'}, ...
                           'tiltMecanico', configRede{n, 'Tilt'}, ...
                           'Tipo', 'isotropic')));
