%--------------------------------------------------------------------------
% Entrada de dados para predição de cobertura
% Rádio FM 102,1 MHz, modelo ITUR P.1812, dados de relevo com resolução de 30 m
% e dados de classificação de estruturas
%--------------------------------------------------------------------------

dadosPredicao = struct('modeloPredicao', 'P.1812', ...
                       'frequencia', 102.1e6, ...
                       'dadosRelevo', 'tests/data/terreno_carangola.tif', ...
                       'dadosClutter', '', ...
                       'Movel', struct('Antena', struct('Altura',  1.6)), ...
                       'Base', struct('Nome', 'FM Carangola', ...
                       'Latitude', -20.725683333333333, ...
                       'Longitude', -42.03616666666667, ...
                       'Potencia', 275.5, ...
                       'Antena', struct('Altura', 8 , ....
                       'ArquivoDados', 'tests/data/AIR6419_B42_NR_dlMacro_H0_V0_3500_PWR.msi', ...
                       'Modelo', 'AIR6419', ...
                       'Funcao', 'TX', ...
                       'Azimute', 0, ...
                       'tiltMecanico', 0, ...
                       'Tipo', 'isotropic')));
