%--------------------------------------------------------------------------
% Entrada de dados para predição de cobertura
% Rádio FM 95,3 MHz, modelo ITUR P.1812, dados de relevo com resolução de 10 m
% e dados de classificação de estruturas, dados sintéticos não condizentes
% com a realidade, criados apenas para verificação
%--------------------------------------------------------------------------

dadosPredicao = struct('modeloPredicao', 'P.1812', ...
                       'frequencia', 95.3e6, ...
                       'dadosRelevo', 'tests/data/b2iseac_rural_land_10km_dem.tif', ...
                       'dadosClutter', 'tests/data/b2iseac_rural_land_10km_clutter.tif', ...
                       'Movel', struct('Antena', struct('Altura',  7.0)), ...
                       'Base', struct('Nome', 'FM', ...
                       'Latitude', -20.72543, ...
                       'Longitude', -42.0854, ...
                       'Potencia', 1000, ...
                       'Antena', struct('Altura', 60 , ....
                       'ArquivoDados', '', ...
                       'Modelo', 'Isotropica', ...
                       'Funcao', 'TX', ...
                       'Azimute', 0, ...
                       'tiltMecanico', 0, ...
                       'Tipo', 'isotropic')));
