%--------------------------------------------------------------------------
% Entrada de dados para predição de cobertura
% à partir de estação do RFDataHub, dados de relevo com resolução de 30 m
% e dados de classificação de estruturas
%--------------------------------------------------------------------------
global RFDataHub

if isempty(RFDataHub)
    load(fullfile('C:\Users\mlnunes\Documents\SupportPackages\tests\','resources', 'RFDataHub.mat'))
end

dadosEstacao = RFDataHub(RFDataHub.Fistel == 50410344001, :);

perdasTX = str2double(string(dadosEstacao.LineAttenuation)) + ...
    str2double(string(dadosEstacao.LineAccessoryLosses));
potTxdBw = 10 * log10(str2double(string(dadosEstacao.TransmitterPower)));
potTxPerdas = 10^((potTxdBw - perdasTX) / 10);

[ganhoH(1, :), ganhoH(2, :)] = model.RFDataHub.parsingAntennaPattern(dadosEstacao.AntennaPattern(1), 360);


dadosAntena = struct('ganho',str2double(string(dadosEstacao.AntennaGain)), ...
                     'ganhoV', [], ...   
                     'ganhoH', ganhoH');



dadosPredicao = struct('modeloPredicao', 'P.1812', ...
                       'frequencia', str2double(string(dadosEstacao.Frequency))*1e6, ...
                       'dadosRelevo', 'tests/data/tv_anhanguera_catalao_dem_clip_30m.tif', ...
                       'dadosClutter', '', ...
                       'Movel', struct('Antena', struct('Altura',  7.0)), ...
                       'Base', struct('Nome', string(dadosEstacao.Name), ...
                       'Latitude', str2double(string(dadosEstacao.Latitude)), ...
                       'Longitude', str2double(string(dadosEstacao.Longitude)), ...
                       'Potencia', potTxPerdas, ...
                       'Antena', struct('Altura', str2double(string(dadosEstacao.AntennaHeight)) , ....
                       'ArquivoDados', dadosAntena, ... 
                       'Modelo', 'Generic', ...
                       'Funcao', 'TX', ...
                       'Azimute', str2double(string(dadosEstacao.AntennaAzimuth)), ...
                       'tiltMecanico', str2double(string(dadosEstacao.AntennaElevation)), ...
                       'Tipo', 'isotropic')));
