%--------------------------------------------------------------------------
% Entrada de dados para predição de cobertura
% Rádio FM 102,1 MHz, modelo ITUR P.1812, dados de relevo com resolução de 10 m
% e dados de classificação de estruturas
%--------------------------------------------------------------------------

dadosPredicao = struct('modeloPredicao', 'P.1812', ...
                       'frequencia', 593e6, ...
                       'dadosRelevo', 'tests/data/tv_anhanguera_catalao_dem_clip_30m.tif', ...
                       'dadosClutter', '', ...
                       'Movel', struct('Antena', struct('Altura',  7.0)), ...
                       'Base', struct('Nome', 'TVD Anhanguera', ...
                       'Latitude', -18.1544, ...
                       'Longitude', -47.9494, ...
                       'Potencia', 77.6, ...
                       'Antena', struct('Altura', 96.5 , ....
                       'ArquivoDados', 'tests/data/ISDE043407EUL.msi', ...
                       'Modelo', 'HCA158-50J', ...
                       'Funcao', 'TX', ...
                       'Azimute', 60, ...
                       'tiltMecanico', 0, ...
                       'Tipo', 'isotropic')));
