function MsiData = getMsiData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AIR6419B42NRDLMACROH0V03500PWR = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  AIR6419B42NRDLMACROH0V03500PWR = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AIR6419B42NRdlMacroH0V03500PWR = importfile("/home/mlnunes/Documentos/dev/matlab/propagação/data/AIR6419_B42_NR_dlMacro_H0_V0_3500_PWR.msi", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Feb-2025 16:42:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["NAME", "Data", "KRD", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "string", "string", "string", "string", "double", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName11", "VarName13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName11", "VarName13"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName4", "VarName10"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName4", "VarName10"], "ThousandsSeparator", ",");

% Import the data
MsiData = readtable(filename, opts);

end